######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 19:18:50 2009
######################################################################

TEMPLATE = subdirs

SUBDIRS = libantimony
SUBDIRS += antimony2sbml
SUBDIRS += sbml2antimony

