#############################################################################
# Makefile for building: testantimony
# Generated by qmake (1.07a) (Qt 3.3.8) on: Mon Mar 02 16:31:12 2009
# Project:  testantimony.pro
# Template: app
# Command: $(QMAKE) "CONFIG-=debug" "CONFIG+=release" -o Makefile testantimony.pro
#############################################################################

####### Compiler, tools and options

CC		=	cl
CXX		=	cl
LEX		= flex
YACC		= byacc
CFLAGS	=	-nologo -Zm200 -wd4996 -W3 -MD -O2  -DUNICODE -DWIN32 -DLIB_EXPORTS -DWIN32
CXXFLAGS	=	-nologo -Zm200 -wd4996 -W3 -w34100 -w34189 -MD -O2  -DUNICODE -DWIN32 -DLIB_EXPORTS -DWIN32
LEXFLAGS	=
YACCFLAGS	=-d
INCPATH	=	 -I"C:\Users\fbergmann\Documents\Visual Studio Codename Orcas\Projects\libsbml\include" -I"C:\Users\fbergmann\Documents\Visual Studio Codename Orcas\Projects\libsbml\include\sbml" -I"." -I"src" -I"." -I"C:\Qt\3.3.8\mkspecs\win32-msvc2005"
LINK	=	link
LFLAGS	=	/NOLOGO /LIBPATH:"C:\Users\fbergmann\Documents\Visual Studio Codename Orcas\Projects\libsbml\win32\bin" /DELAYLOAD:comdlg32.dll /DELAYLOAD:oleaut32.dll /DELAYLOAD:winmm.dll /DELAYLOAD:wsock32.dll /DELAYLOAD:winspool.dll /NODEFAULTLIB:"libc" /SUBSYSTEM:CONSOLE /LIBPATH:"bin"
LIBS	=	 "libsbml3.lib" "antimony.lib"
MOC		=	$(QTDIR)\bin\moc.exe
UIC		=	$(QTDIR)\bin\uic.exe
QMAKE		=	qmake
IDC		=	$(QTDIR)\bin\idc.exe
IDL		=	midl
ZIP		=	zip -r -9
COPY_FILE	=       copy
COPY_DIR	=       copy
DEL_FILE	=       del
DEL_DIR	=       rmdir
MOVE		=       move
CHK_DIR_EXISTS =	if not exist
MKDIR		=	mkdir
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)

####### Files

HEADERS =	src\antimony_api.h \
		src\enums.h \
		src\registry.h \
		src\sbmlx.h \
		src\stringx.h
SOURCES =	src\testantimony.cpp
OBJECTS =	tmp\testantimony.obj
FORMS =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	bin\testantimony.exe

####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

{.}.cpp{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{.}.cc{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{.}.cxx{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{.}.C{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{.}.c{tmp\}.obj::
	$(CC) -c $(CFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{src}.cpp{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{src}.cc{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{src}.cxx{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{src}.C{tmp\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

{src}.c{tmp\}.obj::
	$(CC) -c $(CFLAGS) $(INCPATH) -Fotmp\ @<<
	$<
<<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<< 
	  $(OBJECTS) $(OBJMOC) $(LIBS)
<<


mocables: $(SRCMOC)
uicables: $(UICIMPLS) $(UICDECLS)

Makefile: testantimony.pro  C:\Qt\3.3.8\mkspecs\win32-msvc2005\qmake.conf common.pri
	$(QMAKE) "CONFIG-=debug" "CONFIG+=release" -o Makefile testantimony.pro
qmake: 
	@$(QMAKE) "CONFIG-=debug" "CONFIG+=release" -o Makefile testantimony.pro

dist:
	$(ZIP) testantimony.zip $(SOURCES) $(HEADERS) $(DIST) $(FORMS) C:/Users/fbergmann/Documents/Visual Studio Codename Orcas/Projects/antimony/testantimony.pro common.pri  

uiclean:
mocclean:
clean: uiclean mocclean
	-$(DEL_FILE) tmp\testantimony.obj



FORCE:

distclean: clean
	-$(DEL_FILE) $(TARGET)

####### Compile

tmp\testantimony.obj: src\testantimony.cpp src\antimony_api.h \
		src\registry.h \
		src\stringx.h \
		src\libutil.h \
		src\enums.h \
		src\dnastrand.h \
		src\module.h \
		src\reactantlist.h \
		src\reaction.h \
		src\variable.h \
		src\userfunction.h \
		src\event.h \
		src\formula.h

####### Install

install:  

uninstall:  

