#############################################################################
# Makefile for building: libantimony.1.0.0.dylib
# Generated by qmake (2.01a) (Qt 4.4.2) on: Thu Feb 26 14:29:50 2009
# Project:  antimony.pro
# Template: lib
# Command: /usr/bin/qmake -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx LIBSBML_DIR=/usr/lib -o Makefile antimony.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -arch ppc -arch i386 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -arch ppc -arch i386 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/local/Qt4.4/mkspecs/macx-g++ -I. -I. -Isrc -I.
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch ppc -arch i386 -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libantimony.1.dylib
LIBS          = $(SUBLIBS)   -L/usr/local/lib -L/usr/lib -lsbml
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = src/Antimony.cpp \
		src/antimony_api.cpp \
		src/antimony.tab.cpp \
		src/dnastrand.cpp \
		src/event.cpp \
		src/formula.cpp \
		src/module.cpp \
		src/rd_type.cpp \
		src/reactantlist.cpp \
		src/reaction.cpp \
		src/registry.cpp \
		src/sbmlx.cpp \
		src/stringx.cpp \
		src/testantimony.cpp \
		src/userfunction.cpp \
		src/variable.cpp 
OBJECTS       = tmp/Antimony.o \
		tmp/antimony_api.o \
		tmp/antimony.tab.o \
		tmp/dnastrand.o \
		tmp/event.o \
		tmp/formula.o \
		tmp/module.o \
		tmp/rd_type.o \
		tmp/reactantlist.o \
		tmp/reaction.o \
		tmp/registry.o \
		tmp/sbmlx.o \
		tmp/stringx.o \
		tmp/testantimony.o \
		tmp/userfunction.o \
		tmp/variable.o
DIST          = /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		common.pri \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf \
		antimony.pro
QMAKE_TARGET  = antimony
DESTDIR       = bin/
TARGET        = libantimony.1.0.0.dylib
TARGETA       = bin/libantimony.a
TARGETD       = libantimony.1.0.0.dylib
TARGET0       = libantimony.dylib
TARGET1       = libantimony.1.dylib
TARGET2       = libantimony.1.0.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		ppc \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  bin/$(TARGET)

bin/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) bin/$(TARGET)
	-$(DEL_FILE) bin/$(TARGET0)
	-$(DEL_FILE) bin/$(TARGET1)
	-$(DEL_FILE) bin/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) bin/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: antimony.pro  /usr/local/Qt4.4/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.4/mkspecs/common/unix.conf \
		/usr/local/Qt4.4/mkspecs/common/mac.conf \
		/usr/local/Qt4.4/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.4/mkspecs/qconfig.pri \
		/usr/local/Qt4.4/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.4/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.4/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf \
		common.pri \
		/usr/local/Qt4.4/mkspecs/features/debug.prf \
		/usr/local/Qt4.4/mkspecs/features/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.4/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.4/mkspecs/features/resources.prf \
		/usr/local/Qt4.4/mkspecs/features/uic.prf \
		/usr/local/Qt4.4/mkspecs/features/yacc.prf \
		/usr/local/Qt4.4/mkspecs/features/lex.prf
	$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx LIBSBML_DIR=/usr/lib -o Makefile antimony.pro
/usr/local/Qt4.4/mkspecs/common/unix.conf:
/usr/local/Qt4.4/mkspecs/common/mac.conf:
/usr/local/Qt4.4/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.4/mkspecs/qconfig.pri:
/usr/local/Qt4.4/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.4/mkspecs/features/qt_config.prf:
/usr/local/Qt4.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.4/mkspecs/features/default_pre.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_pre.prf:
common.pri:
/usr/local/Qt4.4/mkspecs/features/debug.prf:
/usr/local/Qt4.4/mkspecs/features/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.4/mkspecs/features/mac/ppc.prf:
/usr/local/Qt4.4/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.4/mkspecs/features/warn_on.prf:
/usr/local/Qt4.4/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.4/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.4/mkspecs/features/resources.prf:
/usr/local/Qt4.4/mkspecs/features/uic.prf:
/usr/local/Qt4.4/mkspecs/features/yacc.prf:
/usr/local/Qt4.4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.4/mkspecs/macx-g++ -macx LIBSBML_DIR=/usr/lib -o Makefile antimony.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/antimony1.0.0 || $(MKDIR) tmp/antimony1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/antimony1.0.0/ && (cd `dirname tmp/antimony1.0.0` && $(TAR) antimony1.0.0.tar antimony1.0.0 && $(COMPRESS) antimony1.0.0.tar) && $(MOVE) `dirname tmp/antimony1.0.0`/antimony1.0.0.tar.gz . && $(DEL_FILE) -r tmp/antimony1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) 
	-$(DEL_FILE) bin/$(TARGET0) bin/$(TARGET1) bin/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

tmp/Antimony.o: src/Antimony.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Antimony.o src/Antimony.cpp

tmp/antimony_api.o: src/antimony_api.cpp src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/registry.h \
		src/dnastrand.h \
		src/module.h \
		src/variable.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/stringx.h \
		src/sbmlx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/antimony_api.o src/antimony_api.cpp

tmp/antimony.tab.o: src/antimony.tab.cpp src/registry.h \
		src/dnastrand.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/antimony.tab.o src/antimony.tab.cpp

tmp/dnastrand.o: src/dnastrand.cpp src/dnastrand.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/dnastrand.o src/dnastrand.cpp

tmp/event.o: src/event.cpp src/event.h \
		src/formula.h \
		src/variable.h \
		src/dnastrand.h \
		src/reaction.h \
		src/rd_type.h \
		src/reactantlist.h \
		src/registry.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/userfunction.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/event.o src/event.cpp

tmp/formula.o: src/formula.cpp src/formula.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/formula.o src/formula.cpp

tmp/module.o: src/module.cpp src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h \
		src/stringx.h \
		src/sbmlx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/module.o src/module.cpp

tmp/rd_type.o: src/rd_type.cpp src/rd_type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/rd_type.o src/rd_type.cpp

tmp/reactantlist.o: src/reactantlist.cpp src/formula.h \
		src/reactantlist.h \
		src/rd_type.h \
		src/registry.h \
		src/dnastrand.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/variable.h \
		src/event.h \
		src/reaction.h \
		src/userfunction.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/reactantlist.o src/reactantlist.cpp

tmp/reaction.o: src/reaction.cpp src/reaction.h \
		src/rd_type.h \
		src/reactantlist.h \
		src/formula.h \
		src/registry.h \
		src/dnastrand.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/variable.h \
		src/event.h \
		src/userfunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/reaction.o src/reaction.cpp

tmp/registry.o: src/registry.cpp src/formula.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h \
		src/sbmlx.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/registry.o src/registry.cpp

tmp/sbmlx.o: src/sbmlx.cpp src/sbmlx.h \
		src/formula.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/reaction.h \
		src/rd_type.h \
		src/reactantlist.h \
		src/registry.h \
		src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/userfunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/sbmlx.o src/sbmlx.cpp

tmp/stringx.o: src/stringx.cpp src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/stringx.o src/stringx.cpp

tmp/testantimony.o: src/testantimony.cpp src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/registry.h \
		src/dnastrand.h \
		src/module.h \
		src/variable.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/testantimony.o src/testantimony.cpp

tmp/userfunction.o: src/userfunction.cpp src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/userfunction.o src/userfunction.cpp

tmp/variable.o: src/variable.cpp src/module.h \
		src/antimony_api.h \
		src/libutil.h \
		src/rd_type.h \
		src/variable.h \
		src/dnastrand.h \
		src/event.h \
		src/formula.h \
		src/reaction.h \
		src/reactantlist.h \
		src/userfunction.h \
		src/registry.h \
		src/stringx.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/variable.o src/variable.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

